/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetDemoRouteImport } from './routes/reset-demo'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChildrenRouteImport } from './routes/children'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIncidentsRouteImport } from './routes/api/incidents'

const ResetDemoRoute = ResetDemoRouteImport.update({
  id: '/reset-demo',
  path: '/reset-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenRoute = ChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsRoute = ApiIncidentsRouteImport.update({
  id: '/api/incidents',
  path: '/api/incidents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/children': typeof ChildrenRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/reset-demo': typeof ResetDemoRoute
  '/api/incidents': typeof ApiIncidentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/children': typeof ChildrenRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/reset-demo': typeof ResetDemoRoute
  '/api/incidents': typeof ApiIncidentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/children': typeof ChildrenRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/reset-demo': typeof ResetDemoRoute
  '/api/incidents': typeof ApiIncidentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/children'
    | '/dashboard'
    | '/debug'
    | '/login'
    | '/logout'
    | '/notifications'
    | '/reports'
    | '/reset-demo'
    | '/api/incidents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/children'
    | '/dashboard'
    | '/debug'
    | '/login'
    | '/logout'
    | '/notifications'
    | '/reports'
    | '/reset-demo'
    | '/api/incidents'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/children'
    | '/dashboard'
    | '/debug'
    | '/login'
    | '/logout'
    | '/notifications'
    | '/reports'
    | '/reset-demo'
    | '/api/incidents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ChildrenRoute: typeof ChildrenRoute
  DashboardRoute: typeof DashboardRoute
  DebugRoute: typeof DebugRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportsRoute: typeof ReportsRoute
  ResetDemoRoute: typeof ResetDemoRoute
  ApiIncidentsRoute: typeof ApiIncidentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-demo': {
      id: '/reset-demo'
      path: '/reset-demo'
      fullPath: '/reset-demo'
      preLoaderRoute: typeof ResetDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children': {
      id: '/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof ChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents': {
      id: '/api/incidents'
      path: '/api/incidents'
      fullPath: '/api/incidents'
      preLoaderRoute: typeof ApiIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ChildrenRoute: ChildrenRoute,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NotificationsRoute: NotificationsRoute,
  ReportsRoute: ReportsRoute,
  ResetDemoRoute: ResetDemoRoute,
  ApiIncidentsRoute: ApiIncidentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
